### ISSUE TITLE
Cannot install Moni on Debian

### ISSUE THREAD

**Issue by brunelloandrea** [maxrossi91/moni#3]
Hello, 

I am having some troubles installing Moni on Debian GNU/Linux 10 (buster).
gcc/g++ version: 8.3.0
clang version: 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
cmake version: 3.25.2

I am cloning the repository, then creating the build directory inside "moni" and, from within "build", running "cmake ..". Then, I get the following warnings:
- Performing Test HAVE___DECLSPEC_DLLEXPORT_ - Failed
- Performing Test HAVE___DECLSPEC_DLLIMPORT_ - Failed

which I assume I can ignore, being on Linux. Then I also get:

- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
- Looking for pthread_create in pthreads - not found
- sdsl-lite not found, building as external content
- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY - Failed
- Performing Test HAVE_PTHREAD_AFFINITY -- failed to compile

which again do not seem to be critical, since the process terminates without errors.

Then, I run make, again from the "build" directory, but here I get the error:
`/moni/build/_deps/pfp_thresholds-src/include/pfp/dictionary.hpp:104:22: error: ‘max’ was not declared in this scope
     auto lcp_right = max(a_in_sa, b_in_sa);
                      ^~~`
If I try to correct it modifying dictionary.hpp, for instance adding "std::" before max, I then get some other errors pertaining to the usage of constant expressions in other files, which I cannot solve... but I assume this is not the correct way to proceed.

Could you help me with this issue?

Thank you!

Andrea

**Comment by maxrossi91** [comment]
Hi, Andrea,

Thank you for reporting this. If you need only to run MONI, you could try to install it from the release assets. We have three ways to install from there, i.e, using

* .sh install (https://github.com/maxrossi91/moni/releases/download/v0.2.0/moni-0.2.0-Linux.sh)
* .tar.gz package (https://github.com/maxrossi91/moni/releases/download/v0.2.0/moni-0.2.0-Linux.tar.gz)
* .deb package (https://github.com/maxrossi91/moni/releases/download/v0.2.0/moni_0.2.0_amd64.deb)

For the error, I think I may have an idea on where it comes from. The inability of using `max` was an issue in `gsa-is` that was fixed by this PR (https://github.com/felipelouza/gsa-is/commit/1a8044df6de57d75e0e45b22720c2cf04b46b9bf). You can try setting the version of gsa-is to `9b229580bea671db24e68f476e6f5d2a5a6360dd` in https://github.com/maxrossi91/moni/blob/ffdb1af54ae5673f2def5231c8afedac64a4cebf/thirdparty/CMakeLists.txt#L55 as `GIT_TAG 9b229580bea671db24e68f476e6f5d2a5a6360dd`. This might solve the issue. (Note that if you do that, you may want to delete the whole build folder and restart from scratch, to ensure cmake downloads the correct version of the repo.)

Bests,

Max

**Comment by brunelloandrea** [comment]
Great, the .sh file worked like a charm... thank you, Max!

Andrea
